#! encoding = utf-8


_LANG_ENG = {
    'main_windowtitle': 'Practice French Conjugaison',
    'status_bar_msg': 'Verify database',
    'config_tm_warning_title': 'Empty',
    'config_tm_warning_body': 'At least one tense mood should be selected. Resume previous configuration',
    'btnOK': 'Okay',
    'btnCancel': 'Cancel',
    'box1_title': 'Forward Practice: Conjugate Verb',
    'box1_btnGen': 'Next',
    'box1_btnCheck': 'Check Answer',
    'box1_btnHelp': 'Help',
    'box2_title': 'Reverse Practice: Guess infinitive, tense and mood',
    'box2_btnGen': 'Next',
    'box2_btnCheck': 'Check Answer',
    'box2_btnHelp': 'Help',
    'box2_lblInf': 'Infinitive: ',
    'box3_title': 'Look Up',
    'box3_btnClear': 'Clear',
    'box3_db_err': "Cannot find verb in glossary",
    'dialog_config_title': 'Select tense and mood to practice',
    'dialog_pref_title': 'Preferences',
    'dialog_pref_lblIntvl': 'Retry interval',
    'dialog_pref_lblIntvl_tooltip': 'Every this number of trials, the verb that fails most will be brought back again',
    'dialog_pref_lblLang': 'Language',
    'dialog_pref_comboLang': ('English', 'Chinese'),
    'dialog_pref_lblFont': 'Font size',
    'dialog_addvoc_title': 'Add verb to glossary',
    'dialog_addvoc_btnAdd': 'Add',
    'dialog_addvoc_btnCancel': 'Cancel',
    'dialog_addvoc_btnUpdate': 'Update',
    'dialog_addvoc_lblVerb': 'Verb',
    'dialog_addvoc_lblExp': 'Explanation',
    'dialog_browse_title': 'Browse glossary',
    'dialog_browse_btnRefresh': 'Refresh',
    'dialog_stats_title': 'Statistics',
    'action_config': 'Config Tense and Mood',
    'action_pref': 'Preference',
    'action_addvoc': 'Add Vocabulary',
    'action_browse': 'Browse Glossary',
    'action_stats': 'Statistics',
    'menu_config': 'Config',
    'menu_glossary': 'Glossary',
    'menu_stats': 'Statistics',
    'status_msg1': ' {:d} entries to practice in forward exercise ',
    'status_msg2': ' {:d} entries to practice in reverse exercise ',
    'msg_warning_title': 'Warning',
    'msg_error_title': 'Error',
    'msg_warning_no_entry': 'No entry found',
    'msg_warning_no_conjug': 'Conjugation not implemented. {:s}',
}

_LANG_CHN = {
    'main_windowtitle': '法语变位练习',
    'status_bar_msg': '验证数据库',
    'config_tm_warning_title': '空',
    'config_tm_warning_body': '至少需要选择一项时态/语态。恢复之前的配置',
    'btnOK': '好',
    'btnCancel': '取消',
    'box1_title': '正向练习：变位一个动词',
    'box1_btnGen': '下一个',
    'box1_btnCheck': '检查回答',
    'box1_btnHelp': '求助',
    'box2_title': '逆向练习：根据变位给出动词原形、时态和语态',
    'box2_btnGen': '下一个',
    'box2_btnCheck': '检查回答',
    'box2_btnHelp': '求助',
    'box2_lblInf': '动词原形: ',
    'box3_title': '查找',
    'box3_btnClear': '清空',
    'box3_db_err': "单词本中找不到该词",
    'dialog_config_title': '选择需要练习的时态和语态',
    'dialog_pref_title': '设置',
    'dialog_pref_lblIntvl': '重试间隔',
    'dialog_pref_lblIntvl_tooltip': '每经过右侧次数的练习，取回当前错误最频繁的动词并重新测试',
    'dialog_pref_lblLang': '语言',
    'dialog_pref_comboLang': ('英语', '汉语'),
    'dialog_pref_lblFont': '字号',
    'dialog_addvoc_title': '添加动词到单词本',
    'dialog_addvoc_btnAdd': '添加',
    'dialog_addvoc_btnCancel': '取消',
    'dialog_addvoc_btnUpdate': '更新',
    'dialog_addvoc_lblVerb': '动词',
    'dialog_addvoc_lblExp': '释义',
    'dialog_browse_title': '浏览单词本',
    'dialog_browse_btnRefresh': '刷新',
    'dialog_stats_title': '统计',
    'action_config': '配置时态和语态',
    'action_pref': '设置',
    'action_addvoc': '添加单词',
    'action_browse': '浏览单词本',
    'action_stats': '统计',
    'menu_config': '配置',
    'menu_glossary': '单词本',
    'menu_stats': '统计',
    'status_msg1': '正向 {:d} 个条目待练习',
    'status_msg2': '逆向 {:d} 个条目待练习',
    'msg_warning_title': '警告',
    'msg_error_title': '错误',
    'msg_warning_no_entry': '未找到条目',
    'msg_warning_no_conjug': '尚未实现该变位类型. {:s}',
}

LANG_PKG = {
    'English': _LANG_ENG,
    'Chinese': _LANG_CHN,
}
