#! encoding = utf-8

import unittest

from dictionary import conjug


class TestConjug(unittest.TestCase):

    def test_present_indicatif(self):

        answer = {
            "aimer": ("j'aime", "tu aimes", "il aime", "elle aime",
                      "nous aimons", "vous aimez", "ils aiment", "elles aiment"),
            "manger": ("je mange", "tu manges", "il mange", "elle mange",
                       "nous mangeons", "vous mangez", "ils mangent", "elles mangent"),
            "partager": ("je partage", "tu partages", "il partage", "elle partage",
                         "nous partageons", "vous partagez", "ils partagent", "elles partagent"),
            "habiter": ("j'habite", "tu habites", "il habite", "elle habite",
                        "nous habitons", "vous habitez", "ils habitent", "elles habitent"),
            "habiller": ("j'habille", "tu habilles", "il habille", "elle habille",
                         "nous habillons", "vous habillez", "ils habillent", "elles habillent"),
            "acheter": ("j'achète", "tu achètes", "il achète", "elle achète",
                        "nous achetons", "vous achetez", "ils achètent", "elles achètent"),
            "préférer": ("je préfère", "tu préfères", "il préfère", "elle préfère",
                         "nous préférons", "vous préférez", "ils préfèrent", "elles préfèrent"),
            "espérer": ("j'espère", "tu espères", "il espère", "elle espère",
                        "nous espérons", "vous espérez", "ils espèrent", "elles espèrent"),
            "atterrir": ("j'atterris", "tu atterris", "il atterrit", "elle atterrit",
                         "nous atterrissons", "vous atterrissez", "ils atterrissent", "elles atterrissent"),
            "choisir": ("je choisis", "tu choisis", "il choisit", "elle choisit",
                        "nous choisissons", "vous choisissez", "ils choisissent", "elles choisissent"),
            "réunir": ("je réunis", "tu réunis", "il réunit", "elle réunit",
                       "nous réunissons", "vous réunissez", "ils réunissent", "elles réunissent"),
            "sertir": ("je sertis", "tu sertis", "il sertit", "elle sertit",
                       "nous sertissons", "vous sertissez", "ils sertissent", "elles sertissent"),
            "se coucher": ("je me couche", "tu te couches", "il se couche", "elle se couche",
                           "nous nous couchons", "vous vous couchez", "ils se couchent", "elles se couchent"),
            "se passer": ("je me passe", "tu te passes", "il se passe", "elle se passe",
                          "nous nous passons", "vous vous passez", "ils se passent", "elles se passent"),
            "s'habiller": ("je m'habille", "tu t'habilles", "il s'habille",
                           "elle s'habille", "nous nous habillons", "vous vous habillez",
                           "ils s'habillent", "elles s'habillent"),
            "s'asseoir": ("je m'assieds", "tu t'assieds", "il s'assied", "elle s'assied",
                          "nous nous asseyons", "vous vous asseyez", "ils s'asseyent", "elles s'asseyent"),
        }

        for root, ans_tuple in answer.items():
            for i, ans in enumerate(ans_tuple):
                test_ans = conjug(root, "présent", "indicatif", i)
                self.assertEqual(test_ans, ans)

    def test_passe_compose_indicatif(self):
        answer = {
            "aimer": ("j'ai aimé", "tu as aimé",
                      "il a aimé", "elle a aimé",
                      "nous avons aimé", "vous avez aimé",
                      "ils ont aimé", "elles ont aimé"),
            "manger": ("j'ai mangé", "tu as mangé",
                       "il a mangé", "elle a mangé",
                       "nous avons mangé", "vous avez mangé",
                       "ils ont mangé", "elles ont mangé"),
            "partager": ("j'ai partagé", "tu as partagé",
                         "il a partagé", "elle a partagé",
                         "nous avons partagé", "vous avez partagé",
                         "ils ont partagé", "elles ont partagé"),
            "habiter": ("j'ai habité", "tu as habité",
                        "il a habité", "elle a habité",
                        "nous avons habité", "vous avez habité",
                        "ils ont habité", "elles ont habité"),
            "habiller": ("j'ai habillé", "tu as habillé",
                         "il a habillé", "elle a habillé",
                         "nous avons habillé", "vous avez habillé",
                         "ils ont habillé", "elles ont habillé"),
            "acheter": ("j'ai acheté", "tu as acheté",
                        "il a acheté", "elle a acheté",
                        "nous avons acheté", "vous avez acheté",
                        "ils ont acheté", "elles ont acheté"),
            "préférer": ("j'ai préféré", "tu as préféré",
                         "il a préféré", "elle a préféré",
                         "nous avons préféré", "vous avez préféré",
                         "ils ont préféré", "elles ont préféré"),
            "espérer": ("j'ai espéré", "tu as espéré",
                        "il a espéré", "elle a espéré",
                        "nous avons espéré", "vous avez espéré",
                        "ils ont espéré", "elles ont espéré"),
            "atterrir": ("j'ai atterri", "tu as atterri",
                         "il a atterri", "elle a atterri",
                         "nous avons atterri", "vous avez atterri",
                         "ils ont atterri", "elles ont atterri"),
            "choisir": ("j'ai choisi", "tu as choisi",
                        "il a choisi", "elle a choisi",
                        "nous avons choisi", "vous avez choisi",
                        "ils ont choisi", "elles ont choisi"),
            "réunir": ("j'ai réuni", "tu as réuni",
                       "il a réuni", "elle a réuni",
                       "nous avons réuni", "vous avez réuni",
                       "ils ont réuni", "elles ont réuni"),
            "sertir": ("j'ai serti", "tu as serti",
                       "il a serti", "elle a serti",
                       "nous avons serti", "vous avez serti",
                       "ils ont serti", "elles ont serti"),
            "se coucher": ("je me suis couché(e)", "tu t'es couché(e)",
                           "il s'est couché", "elle s'est couchée",
                           "nous nous sommes couché(e)s", "vous vous êtes couché(e)s",
                           "ils se sont couchés", "elles se sont couchées"),
            "se passer": ("je me suis passé(e)", "tu t'es passé(e)",
                          "il s'est passé", "elle s'est passée",
                          "nous nous sommes passé(e)s", "vous vous êtes passé(e)s",
                          "ils se sont passés", "elles se sont passées"),
            "s'habiller": ("je me suis habillé(e)", "tu t'es habillé(e)",
                           "il s'est habillé", "elle s'est habillée",
                           "nous nous sommes habillé(e)s", "vous vous êtes habillé(e)s",
                           "ils se sont habillés", "elles se sont habillées"),
            "s'asseoir": ("je me suis assis(e)", "tu t'es assis(e)",
                          "il s'est assis", "elle s'est assise",
                          "nous nous sommes assis(es)", "vous vous êtes assis(es)",
                          "ils se sont assis", "elles se sont assises"),
        }
        for root, ans_tuple in answer.items():
            for i, ans in enumerate(ans_tuple):
                test_ans = conjug(root, "passé composé", "indicatif", i)
                self.assertEqual(test_ans, ans)

    def test_imparfait_indicatif(self):
        answer = {
            "aimer": ("j'aimais", "tu aimais",
                      "il aimait", "elle aimait",
                      "nous aimions", "vous aimiez",
                      "ils aimaient", "elles aimaient"),
            "manger": ("je mangeais", "tu mangeais",
                       "il mangeait", "elle mangeait",
                       "nous mangions", "vous mangiez",
                       "ils mangeaient", "elles mangeaient"),
            "partager": ("je partageais", "tu partageais",
                         "il partageait", "elle partageait",
                         "nous partagions", "vous partagiez",
                         "ils partageaient", "elles partageaient"),
            "habiter": ("j'habitais", "tu habitais",
                        "il habitait", "elle habitait",
                        "nous habitions", "vous habitiez",
                        "ils habitaient", "elles habitaient"),
            "habiller": ("j'habillais", "tu habillais",
                         "il habillait", "elle habillait",
                         "nous habillions", "vous habilliez",
                         "ils habillaient", "elles habillaient"),
            "acheter": ("j'achetais", "tu achetais",
                        "il achetait", "elle achetait",
                        "nous achetions", "vous achetiez",
                        "ils achetaient", "elles achetaient"),
            "préférer": ("je préférais", "tu préférais",
                         "il préférait", "elle préférait",
                         "nous préférions", "vous préfériez",
                         "ils préféraient", "elles préféraient"),
            "espérer": ("j'espérais", "tu espérais",
                        "il espérait", "elle espérait",
                        "nous espérions", "vous espériez",
                        "ils espéraient", "elles espéraient"),
            "atterrir": ("j'atterrissais", "tu atterrissais",
                         "il atterrissait", "elle atterrissait",
                         "nous atterrissions", "vous atterrissiez",
                         "ils atterrissaient", "elles atterrissaient"),
            "choisir": ("je choisissais", "tu choisissais",
                        "il choisissait", "elle choisissait",
                        "nous choisissions", "vous choisissiez",
                        "ils choisissaient", "elles choisissaient"),
            "réunir": ("je réunissais", "tu réunissais",
                       "il réunissait", "elle réunissait",
                       "nous réunissions", "vous réunissiez",
                       "ils réunissaient", "elles réunissaient"),
            "sertir": ("je sertissais", "tu sertissais",
                       "il sertissait", "elle sertissait",
                       "nous sertissions", "vous sertissiez",
                       "ils sertissaient", "elles sertissaient"),
            "se coucher": ("je me couchais", "tu te couchais",
                           "il se couchait", "elle se couchait",
                           "nous nous couchions", "vous vous couchiez",
                           "ils se couchaient", "elles se couchaient"),
            "se passer": ("je me passais", "tu te passais",
                          "il se passait", "elle se passait",
                          "nous nous passions", "vous vous passiez",
                          "ils se passaient", "elles se passaient"),
            "s'habiller": ("je m'habillais", "tu t'habillais",
                           "il s'habillait", "elle s'habillait",
                           "nous nous habillions", "vous vous habilliez",
                           "ils s'habillaient", "elles s'habillaient"),
            "s'asseoir": ("je m'asseyais", "tu t'asseyais",
                          "il s'asseyait", "elle s'asseyait",
                          "nous nous asseyions", "vous vous asseyiez",
                          "ils s'asseyaient", "elles s'asseyaient"),
        }
        for root, ans_tuple in answer.items():
            for i, ans in enumerate(ans_tuple):
                test_ans = conjug(root, "imparfait", "indicatif", i)
                self.assertEqual(test_ans, ans)

    def test_future_indicatif(self):
        answer = {
            "aimer": ("j'aimerai", "tu aimeras",
                      "il aimera", "elle aimera",
                      "nous aimerons", "vous aimerez",
                      "ils aimeront", "elles aimeront"),
            "manger": ("je mangerai", "tu mangeras",
                       "il mangera", "elle mangera",
                       "nous mangerons", "vous mangerez",
                       "ils mangeront", "elles mangeront"),
            "partager": ("je partagerai", "tu partageras",
                         "il partagera", "elle partagera",
                         "nous partagerons", "vous partagerez",
                         "ils partageront", "elles partageront"),
            "habiter": ("j'habiterai", "tu habiteras",
                        "il habitera", "elle habitera",
                        "nous habiterons", "vous habiterez",
                        "ils habiteront", "elles habiteront"),
            "habiller": ("j'habillerai", "tu habilleras",
                         "il habillera", "elle habillera",
                         "nous habillerons", "vous habillerez",
                         "ils habilleront", "elles habilleront"),
            "acheter": ("j'achèterai", "tu achèteras",
                        "il achètera", "elle achètera",
                        "nous achèterons", "vous achèterez",
                        "ils achèteront", "elles achèteront"),
            "préférer": ("je préférerai", "tu préféreras",
                         "il préférera", "elle préférera",
                         "nous préférerons", "vous préférerez",
                         "ils préféreront", "elles préféreront"),
            "espérer": ("j'espérerai", "tu espéreras",
                        "il espérera", "elle espérera",
                        "nous espérerons", "vous espérerez",
                        "ils espéreront", "elles espéreront"),
            "atterrir": ("j'atterrirai", "tu atterriras",
                         "il atterrira", "elle atterrira",
                         "nous atterrirons", "vous atterrirez",
                         "ils atterriront", "elles atterriront"),
            "choisir": ("je choisirai", "tu choisiras",
                        "il choisira", "elle choisira",
                        "nous choisirons", "vous choisirez",
                        "ils choisiront", "elles choisiront"),
            "réunir": ("je réunirai", "tu réuniras",
                       "il réunira", "elle réunira",
                       "nous réunirons", "vous réunirez",
                       "ils réuniront", "elles réuniront"),
            "sertir": ("je sertirai", "tu sertiras",
                       "il sertira", "elle sertira",
                       "nous sertirons", "vous sertirez",
                       "ils sertiront", "elles sertiront"),
            "se coucher": ("je me coucherai", "tu te coucheras",
                           "il se couchera", "elle se couchera",
                           "nous nous coucherons", "vous vous coucherez",
                           "ils se coucheront", "elles se coucheront"),
            "se passer": ("je me passerai", "tu te passeras",
                          "il se passera", "elle se passera",
                          "nous nous passerons", "vous vous passerez",
                          "ils se passeront", "elles se passeront",),
            "s'habiller": ("je m'habillerai", "tu t'habilleras",
                           "il s'habillera", "elle s'habillera",
                           "nous nous habillerons", "vous vous habillerez",
                           "ils s'habilleront", "elles s'habilleront"),
            "s'asseoir": ("je m'asseyerai", "tu t'asseyeras",
                          "il s'asseyera", "elle s'asseyera",
                          "nous nous asseyerons", "vous vous asseyerez",
                          "ils s'asseyerent", "elles s'asseyerent"),
        }
        for root, ans_tuple in answer.items():
            for i, ans in enumerate(ans_tuple):
                test_ans = conjug(root, "futur", "indicatif", i)
                self.assertEqual(test_ans, ans)


if __name__ == '__main__':
    unittest.main()
